import random

# List of 1,000 compliments
compliments = [
    "You're more loveable than a Squishmallow, and you have arms.",
    "Your smile could make a traffic jam feel like a parade.",
    "You're the human equivalent of finding money in your pocket.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "You make Excel spreadsheets look exciting.",
    "You're like a perfectly toasted marshmallow: warm, sweet, and rare to find done just right.",
    "Your jokes are so good, even my spam folder would open them.",
    "You're the reason aliens haven't given up on humanity yet.",
    "If compliments were currency, you'd break the economy.",
    "You're more refreshing than the cold side of the pillow.",
    "Even my WiFi connects better when you're around.",
    "If you were a font, you'd be the one everyone wishes they'd chosen.",
    "Your presence is like finding the perfect parking spot.",
    "You're like a good cup of coffee – strong, warm, and able to get me through the day.",
    "Your laugh is my favorite notification sound.",
    "You've got more charm than a bracelet factory.",
    "You're the human equivalent of a pizza that actually looks like the advertisement.",
    "Your fashion sense is so good, mannequins take notes.",
    "You're like the last piece of chocolate I've been saving – simply the best part of my day.",
    "Your dance moves would make even GPS say 'recalculating.'",
    "You're so cool, penguins ask you for advice.",
    "If people were cookies, you'd be the one with extra chocolate chips.",
    "Your intelligence is so bright, I need sunglasses just to listen to you.",
    "You're the reason dictionaries need more positive words.",
    "Your outfit is so sharp, it could slice a pineapple.",
    "If personalities were ice cream flavors, you'd be everyone's favorite.",
    "You're like a perfect avocado – rare and worth the search.",
    "You're more dependable than my alarm clock, and way more pleasant.",
    "Your puns are so good, even dads slow-clap.",
    "If life were a movie, you'd be the scene everyone quotes.",
    "You're the human equivalent of getting an extra chicken nugget in your order.",
    "Your ideas are like fireworks – brilliant, exciting, and make everyone look up.",
    "You have the organizational skills that Marie Kondo dreams about.",
    "You're like finding the perfect GIF for a text conversation.",
    "Your taste in music should come with its own radio station.",
    "You're smoother than sliding into freshly washed sheets.",
    "If enthusiasm were a person, it would ask for your autograph.",
    "You make Monday mornings feel like Friday afternoons.",
    "Your optimism could power a small city.",
    "You're like a Swiss Army knife of awesome – useful in every situation.",
    "If high-fives were people, they'd be you.",
    "Your creativity makes Jackson Pollock look indecisive.",
    "You're the real-life version of the '100' emoji.",
    "Your cooking makes restaurant chefs question their career choices.",
    "You're more comforting than fuzzy socks in winter.",
    "Your attention to detail makes Where's Waldo nervous.",
    "You're like bubble wrap – fun to be around and relieves stress.",
    "Your handwriting should be a downloadable font.",
    "You're the reason autocorrect can't replace human connection.",
    "Your pet-naming skills deserve their own TED Talk.",
    "You're sharper than a No. 2 pencil on test day.",
    "Your presence makes plants grow faster – that's how radiant you are.",
    "You rock argyle socks better than anyone I know.",
    "Your voice would make audiobook listeners hit the 'repeat' button.",
    "You're the human version of finding the perfect meme.",
    "Your patience makes waiting rooms feel like spas.",
    "You're like a good book – engaging, hard to put down, and leaves a lasting impression.",
    "Your eye contact game is stronger than my Wi-Fi connection.",
    "You're more refreshing than the first sip of a cold drink on a hot day.",
    "Your memory makes elephants jealous.",
    "You're the reason why aliens would say 'take me to your leader.'",
    "Your logic would make Sherlock Holmes do a double-take.",
    "You're like a superhero, but your power is making everyone feel valued.",
    "Your positive attitude is more contagious than a yawn in a crowded elevator.",
    "You're the person dogs get excited to see at the park.",
    "Your travel stories should have their own Netflix series.",
    "You make small talk feel like a TED Talk.",
    "You're more appealing than pizza at a vegetable convention.",
    "Your playlist could cure a bad mood in 2.5 songs.",
    "You're so thoughtful, I bet you help shopping carts find their way home.",
    "Your backup plans have backup plans that have backup plans.",
    "You're like a walking comfort blanket in human form.",
    "Your advice deserves its own advice column.",
    "You're the reason thesauruses need more synonyms for 'amazing.'",
    "Your emoji usage should be studied in communication classes.",
    "You're like finding the matching sock immediately – rare and wonderful.",
    "Your focus makes meditation gurus take notes.",
    "You're the person everyone hopes is attending the party.",
    "Your kindness makes Mister Rogers look like a rookie.",
    "You're more reliable than gravity and twice as attractive.",
    "Your problem-solving skills make maze designers reconsider their career.",
    "You're like a perfect high-five that makes the perfect sound.",
    "Your wit is so sharp, it needs a warning label.",
    "You're the human equivalent of finding the long French fry in your order.",
    "Your patience makes waiting for websites to load seem exciting.",
    "You're more precise than a surgeon with a steady hand.",
    "Your cooking should have its own Michelin star category.",
    "You're like a dessert that somehow has zero calories.",
    "Your generosity makes Santa Claus look selfish.",
    "You're more exciting than bubble wrap with extra-large bubbles.",
    "Your style is what fashion magazines aspire to feature.",
    "You're like the perfect Netflix recommendation – always what I didn't know I needed.",
    "Your hugs should be measured in therapeutic units.",
    "You're more fascinating than watching paint dry in reverse.",
    "Your jokes age like fine wine, getting better each time I think about them.",
    "You're the human version of that perfect song lyric that gives you chills.",
    "Your enthusiasm makes pep rallies look depressing.",
    "You're more intuitive than autocomplete on my most-used phrases.",
    "Your conversation skills should be bottled and sold as a social elixir.",
    "You're like the perfect weather day that makes everyone want to go outside.",
    "Your confidence could power a rocket to Mars.",
    "You're more helpful than finding a flashlight during a power outage.",
    "Your commitment makes wedding vows sound casual.",
    "You're like a phone that never needs charging – full of endless energy.",
    "Your creativity deserves its own museum wing.",
    "You're more reliable than my internet provider claims to be.",
    "Your smile rivals the brightness setting on my phone at 3 AM.",
    "You're like finding money in a coat I haven't worn in months.",
    "Your determination makes marathoners look lazy.",
    "You're more soothing than ASMR videos of slicing kinetic sand.",
    "Your efficiency would make Henry Ford jealous.",
    "You're like my favorite song on repeat – never gets old.",
    "Your personality is the perfect mix of Netflix and chill.",
    "You're more entertaining than watching squirrels trying to remember where they buried their nuts.",
    "Your courage makes lion tamers look timid.",
    "You're like finding the missing puzzle piece under the couch – the perfect fit and such a relief.",
    "Your compassion makes therapy sessions feel redundant.",
    "You're more balanced than a tightrope walker with a physics degree.",
    "Your curiosity would make cats reconsider their life choices.",
    "You're like a phone that autocorrects to what I actually meant.",
    "Your cooking deserves its own Instagram filter.",
    "You're more engaging than a ring in a proposal.",
    "Your work ethic makes bees look like they're on permanent vacation.",
    "You're like a weighted blanket – comforting and somehow exactly what everyone needs.",
    "Your insight is sharper than a new pair of scissors cutting wrapping paper.",
    "You're more consistent than my coffee addiction.",
    "Your storytelling makes audiobook narrators sound monotone.",
    "You're like a freshly baked cookie – warm and making everything better.",
    "Your resourcefulness would impress MacGyver.",
    "You're more authentic than organic, locally-sourced, farm-to-table produce.",
    "Your ambition makes overachievers feel inadequate.",
    "You're like a perfectly ripe avocado – rare and worth celebrating.",
    "Your attention span in boring meetings deserves an Olympic medal.",
    "You're more quotable than a book of famous sayings.",
    "Your reliability makes Swiss watches seem flakey.",
    "You're like a surprise day off work – unexpected and wonderful.",
    "Your spontaneity makes adventure seekers look boring.",
    "You're more impressive than parallel parking on the first try.",
    "Your timing is better than the punchline of a well-crafted joke.",
    "You're like a phone with full bars and 100% battery – optimally functional.",
    "Your taste buds should be insured for millions.",
    "You're more healing than aloe vera on a sunburn.",
    "Your coordination makes professional dancers jealous.",
    "You're like finding a shortcut home during rush hour – a blessing to all.",
    "Your adaptability would impress chameleons.",
    "You're more valuable than cryptocurrency at its peak.",
    "Your thoughtfulness makes greeting card writers look lazy.",
    "You're like the perfect temperature shower – rare and absolutely perfect.",
    "Your social skills could sell ice to polar bears.",
    "You're more organized than a library run by obsessive-compulsives.",
    "Your honesty makes lie detectors obsolete.",
    "You're like finding exact change in my pocket – convenient and satisfying.",
    "Your resilience makes rubber bands seem brittle.",
    "You're more supportive than expensive orthopedic shoes.",
    "Your wisdom makes fortune cookies seem shallow.",
    "You're like the last cookie that everyone wanted but didn't take – a treasure.",
    "Your time management could organize New Year's Eve.",
    "You're more surprising than plot twists in mystery novels.",
    "Your gentleness would make a butterfly feel like a bulldozer.",
    "You're like a playlist that perfectly matches my mood – always just right.",
    "Your handshake conveys more character than most people's autobiographies.",
    "You're more impressive than someone who actually reads the terms and conditions.",
    "Your navigation skills would render GPS speechless.",
    "You're like a dream that I'm happy I remembered – delightful and meaningful.",
    "Your charisma makes celebrities study your technique.",
    "You're more magnetic than the North Pole.",
    "Your taste in art makes museum curators second-guess their exhibits.",
    "You're like finding a parking spot right in front of the destination.",
    "Your strength makes gym enthusiasts question their routines.",
    "You're more decisive than a judge with a deadline.",
    "Your empathy makes therapists take notes.",
    "You're like a battery that never loses its charge – consistently powerful.",
    "Your sincerity makes politicians look like amateurs.",
    "You're more captivating than the season finale of my favorite show.",
    "Your integrity would make Honest Abe request pointers.",
    "You're like a warm blanket on a cold morning – exactly what everyone needs.",
    "Your ingenuity makes inventors jealous.",
    "You're more practical than Swiss Army knife with extra attachments.",
    "Your perspective makes philosophers reconsider their theories.",
    "You're like a plot twist that improves the whole story – unexpected but perfect.",
    "Your gratitude makes thanksgiving dinner feel ungrateful.",
    "You're more inspiring than motivational posters in a gym.",
    "Your awareness makes ninjas seem oblivious.",
    "You're like the first sip of coffee in the morning – life-changing.",
    "Your creativity makes art museums consider renovations.",
    "You're more relaxing than a spa day with extra massages.",
    "Your sophistication makes wine tastings feel like juice boxes.",
    "You're like finding the cool spot on the pillow – refreshing and perfect.",
    "Your passion makes Romeo and Juliet look uncommitted.",
    "You're more reliable than sunrise predictions.",
    "Your charm makes fairy tales seem ordinary.",
    "You're like the perfect amount of sauce on pasta – just right.",
    "Your consideration makes Emily Post look rude.",
    "You're more intriguing than conspiracy theories at 3 AM.",
    "Your loyalty makes dogs look uncommitted.",
    "You're like a perfectly sharp pencil – on point and ready for anything.",
    "Your authenticity makes truth serums unnecessary.",
    "You're more refreshing than air conditioning in August.",
    "Your resourcefulness makes survival experts look unprepared.",
    "You're like a surprise upgrade to first class – unexpected and fantastic.",
    "Your articulation makes dictionaries feel incomplete.",
    "You're more grounded than gravity itself.",
    "Your thoughtfulness makes gift registries obsolete.",
    "You're like finding extra fries at the bottom of the bag – a happy surprise.",
    "Your intelligence makes encyclopedias feel insecure.",
    "You're more adaptable than a universal remote control.",
    "Your judgment makes Supreme Court justices second-guess themselves.",
    "You're like a comfortable chair that also looks stylish – functional and impressive.",
    "Your problem-solving abilities would make Einstein proud.",
    "You're more insightful than fortune tellers with crystal balls.",
    "Your friendliness makes hospitality professionals look standoffish.",
    "You're like the perfect amount of sleep – rejuvenating and satisfying.",
    "Your stability makes gyroscopes seem wobbly.",
    "You're more motivating than coffee on Monday morning.",
    "Your discipline makes drill sergeants look lenient.",
    "You're like a perfectly timed joke – landing at exactly the right moment.",
    "Your attention to others makes hosts feel like guests.",
    "You're more impressive than someone who folds fitted sheets correctly.",
    "Your logic would make Spock raise both eyebrows.",
    "You're like a Swiss watch – precise and admired worldwide.",
    "Your style makes fashion magazines consider new categories.",
    "You're more comforting than chicken soup during a cold.",
    "Your vision makes eagles feel nearsighted.",
    "You're like a palindrome – impressive in any direction.",
    "Your perseverance makes marathon runners look like quitters.",
    "You're more enlightening than libraries with the lights on.",
    "Your serenity would make meditation gurus request lessons.",
    "You're like a perfect sunset – beautiful and worth stopping to appreciate.",
    "Your thoroughness makes detailed people look careless.",
    "You're more organized than alphabetized spice racks.",
    "Your dependability makes the atomic clock seem unreliable.",
    "You're like a compass that always points to awesome.",
    "Your authenticity makes truth seem like it's trying too hard.",
    "You're more entertaining than a three-ring circus with extra rings.",
    "Your punctuality makes time itself check its watch.",
    "You're like a secret ingredient that improves every recipe.",
    "Your accountability makes referees look biased.",
    "You're more versatile than a multi-tool with extra functions.",
    "Your originality makes creativity jealous.",
    "You're like a perfect haircut – making everything else look better.",
    "Your dynamism makes energy drinks seem like decaf.",
    "You're more motivating than deadline extensions.",
    "Your pragmatism makes efficiency experts take notes.",
    "You're like a four-leaf clover – rare and bringing good things.",
    "Your clarity makes crystal look cloudy.",
    "You're more impressive than someone who reads the entire manual first.",
    "Your mindfulness makes meditation apps feel stressed.",
    "You're like a telescope that sees possibilities others miss.",
    "Your positivity could power the national grid during outages.",
    "You're more stimulating than espresso shots at midnight.",
    "Your tact makes diplomats request pointers.",
    "You're like the perfect playlist for any occasion – always appropriate and enjoyable.",
    "Your competence makes professionals look like amateurs.",
    "You're more calming than watching fish in an aquarium.",
    "Your dedication makes Olympic athletes question their commitment.",
    "You're like a universal adapter – fitting perfectly in any situation.",
    "Your consistency makes metronomes seem random.",
    "You're more uplifting than helium balloons at a birthday party.",
    "Your resilience makes trampolines seem rigid.",
    "You're like a favorite book that reveals something new with each reading.",
    "Your generosity makes philanthropists look stingy.",
    "You're more influential than trending hashtags.",
    "Your confidence makes mountains look insecure about their height.",
    "You're like a perfect cup of tea – comforting and exactly what's needed.",
    "Your cheerfulness makes sunshine seem gloomy.",
    "You're more valuable than rare collectibles at auction.",
    "Your magnetism attracts more than just refrigerator art.",
    "You're like a sought-after vintage item – timeless and increasing in value.",
    "Your cleverness makes riddles feel obvious.",
    "You're more helpful than tutorials with slow-motion demonstrations.",
    "Your persuasiveness could sell silence to a podcast host.",
    "You're like a favorite song that never gets skipped – always welcome.",
    "Your determination makes brick walls reconsider their solidity.",
    "You're more accurate than weather forecasts for the current moment.",
    "Your foresight makes psychics question their abilities.",
    "You're like the perfect temperature hot tub – immediately relaxing.",
    "Your fortitude makes mountains look like speed bumps.",
    "You're more prepared than Boy Scouts with extra badges.",
    "Your composure makes yoga instructors seem twitchy.",
    "You're like a dictionary that also includes the perfect words that don't exist yet.",
    "Your spontaneity makes improv actors seem scripted.",
    "You're more engaging than cliffhangers in season finales.",
    "Your politeness makes etiquette books feel unnecessary.",
    "You're like a universal remote that actually works – solving problems effortlessly.",
    "Your imagination makes fantasy authors consult you for ideas.",
    "You're more dynamic than firework finales on New Year's Eve.",
    "Your wit makes Oscar Wilde seem unfunny.",
    "You're like a warm cookie fresh from the oven of personality.",
    "Your steadfastness makes mountains envious.",
    "You're more insightful than fortune cookies after a philosophy convention.",
    "Your harmony makes orchestras sound out of tune.",
    "You're like finding the perfect gif for a text conversation – exactly right.",
    "Your decency makes saints look questionable.",
    "You're more refreshing than mint gum after garlic bread.",
    "Your perspective gives viewpoints an inferiority complex.",
    "You're like a phone that answers exactly when I'm looking for it – reliable.",
    "Your thoughtfulness makes greeting cards seem impersonal.",
    "You're more dazzling than disco balls under spotlights.",
    "Your clarity makes crystal balls ask for cleaning tips.",
    "You're like the perfect pen that never skips or blobs – consistently excellent.",
    "Your genuineness makes authenticity certificates look suspicious.",
    "You're more awesome than a possum wearing an awesome blossom.",
    "Your encouragement makes pep rallies look depressing.",
    "You're like the exact change needed for exact change required – perfectly prepared.",
    "Your intelligence makes encyclopedias consult you for fact-checking.",
    "You're more surprising than plot twists in thriller movies.",
    "Your thoughtful nature makes Buddhists seem hasty.",
    "You're like a warm sweater that's also fashionable – practical and impressive.",
    "Your dedication makes monks question their commitment.",
    "You're more valuable than printer ink by volume.",
    "Your attention to detail makes microscopes feel inadequate.",
    "You're like a vacation day that doesn't count against your time off – a bonus to all.",
    "Your sense of direction would put GPS to shame.",
    "You're more appealing than free samples at a gourmet food store.",
    "Your hospitality makes luxury hotels seem unwelcoming.",
    "You're like a perfect hair day during important events – reliable when it counts.",
    "Your sincerity makes truth serums redundant.",
    "You're more stable than chemical elements with full outer shells.",
    "Your consideration makes Miss Manners look thoughtless.",
    "You're like a battery that charges other batteries – energizing everyone around you.",
    "Your persistence makes marathoners look like sprinters.",
    "You're more perceptive than high-powered telescopes.",
    "Your adaptability makes chameleons look stubborn.",
    "You're like a comfortable silence – peaceful and never awkward.",
    "Your dynamism makes espresso seem decaffeinated.",
    "You're more brilliant than a diamond under spotlights.",
    "Your balance makes tightrope walkers look wobbly.",
    "You're like a perfect synonym when the first word isn't quite right – exactly what's needed.",
    "Your conscientiousness makes perfectionists feel sloppy.",
    "You're more appealing than cake at a diet convention.",
    "Your principles make moral philosophers reconsider their theories.",
    "You're like a perfect Wi-Fi connection – reliable and making everything better.",
    "Your motivation makes caffeine feel unnecessary.",
    "You're more practical than duct tape in an emergency kit.",
    "Your focus makes laser beams seem scattered.",
    "You're like the perfect parking spot – a rare find worth celebrating.",
    "Your integrity makes truth itself more believable.",
    "You're more versatile than a reversible jacket with pockets.",
    "Your ambition makes overachievers look unmotivated.",
    "You're like a favorite movie that gets better with each viewing – full of new discoveries.",
    "Your efficiency makes assembly lines look wasteful.",
    "You're more valuable than exclusive collectors' editions.",
    "Your warmth makes summer feel jealous.",
    "You're like a well-timed compliment – arriving exactly when needed.",
    "Your spirit makes enthusiasm look lethargic.",
    "You're more reliable than gravity in physics equations.",
    "Your intuition makes fortune tellers question their career choice.",
    "You're like the perfect playlist shuffle – consistently delivering just what's needed.",
    "Your calmness makes yoga instructors envious.",
    "You're more interesting than conspiracy theories after midnight.",
    "Your authenticity makes truth detectors malfunction from overload.",
    "You're like a perfect metaphor – making complex things understandable.",
    "Your insight makes therapists book appointments with you.",
    "You're more constant than the speed of light in a vacuum.",
    "Your strength makes superheroes reconsider their potential.",
    "You're like the perfect amount of topping – enhancing without overwhelming.",
    "Your clarity makes crystal balls look cloudy.",
    "You're more precise than atomic clocks during leap seconds.",
    "Your passion makes motivational speakers take notes.",
    "You're like a perfect circle – well-rounded in every way.",
    "Your dedication makes workaholics look lazy.",
    "You're more valuable than collector's items still in the original packaging.",
    "Your zest makes lemons reconsider their purpose.",
    "You're like a perfect analogy – making difficult concepts instantly clear.",
    "Your patience would outlast geological formations.",
    "You're more refreshing than mints after garlic bread.",
    "Your originality makes innovation look derivative.",
    "You're like a perfect pair of jeans – reliable, comfortable, and making everything look good.",
    "Your foresight makes prophets check their predictions twice.",
    "You're more engaging than binge-worthy TV series finales.",
    "Your precision makes laser-guided missiles recalculate.",
    "You're like the perfect umbrella – there when needed and never forgotten elsewhere.",
    "Your brilliance makes diamonds look like cubic zirconia.",
    "You're more consistent than the earth's rotation.",
    "Your wisdom makes ancient philosophers consult their notes.",
    "You're like a perfect alignment of stars – rare and significant.",
    "Your vision makes eagles squint in inadequacy.",
    "You're more multifaceted than expertly cut gemstones.",
    "Your honesty makes truth feel like it needs to up its game.",
    "You're like a perfect pair of headphones – blocking out the noise and delivering the good stuff.",
    "Your radiance makes the sun consider wearing sunglasses.",
    "You're more balanced than tightrope walkers with counterweights.",
    "Your logic makes supercomputers perform double-checks.",
    "You're like a perfect temperature fridge – keeping everything just right.",
    "Your courage makes lion tamers feel timid.",
    "You're more impressive than magicians with sleeves rolled up.",
    "Your generosity makes philanthropy foundations reassess their donation levels.",
    "You're like a perfect cup of coffee – energizing and making everything better.",
    "Your depth makes oceans feel shallow.",
    "You're more interesting than books that keep you up all night.",
    "Your resilience makes rubber bands look brittle.",
    "You're like a perfect spice blend – enhancing everything you're added to.",
    "Your charm makes charisma take charm lessons.",
    "You're more entertaining than streaming services with unlimited content.",
    "Your ingenuity makes inventors patent your conversations.",
    "You're like a perfect password – uniquely valuable and impossible to replicate.",
    "Your perceptiveness makes psychics close up shop.",
    "You're more refreshing than jumping into a pool on a hot day.",
    "Your creativity makes art jealous of your everyday thinking.",
    "You're like a perfect recipe – bringing all the right elements together.",
    "Your confidence makes mountains feel small.",
    "You're more interesting than documentaries people actually finish watching.",
    "Your wit could solve crossword puzzles without looking at the clues.",
    "You're like a perfect autoplay suggestion – exactly what I didn't know I needed.",
    "Your energy makes power plants seem inefficient.",
    "You're more reliable than schedules in German train stations.",
    "Your gentleness makes feathers feel heavy-handed.",
    "You're like a perfect plot twist – unexpected and improving the whole story.",
    "Your authenticity makes truth feel like it's trying too hard.",
    "You're more valuable than limited edition anything.",
    "Your enthusiasm makes cheerleaders look unenthusiastic.",
    "You're like a perfect sweater – comforting, flattering, and exactly what's needed.",
    "Your curiosity makes exploration seem unambitious.",
    "You're more quotable than famous speeches.",
    "Your positivity makes optimism look pessimistic.",
    "You're like a perfect sunset – worth stopping everything to appreciate.",
    "Your intellect makes libraries feel like they need more books.",
    "You're more exciting than roller coasters with extra loops.",
    "Your dependability makes constants in physics equations double-check themselves.",
    "You're like a perfect thermostat – creating the ideal environment wherever you go.",
    "Your graciousness makes etiquette experts take notes.",
    "You're more magnetic than industrial strength magnets.",
    "Your thoroughness makes detailed people look careless.",
    "You're like a perfect movie sequel – even better than the original.",
    "Your focus makes meditation masters feel scattered.",
    "You're more reliable than backup generators during power outages.",
    "Your adaptability makes evolution reconsider its timeline.",
    "You're like a perfect camera focus – highlighting exactly what matters.",
    "Your consideration makes thoughtfulness feel shallow.",
    "You're more impressive than world records with wide margins.",
    "Your harmony makes symphony orchestras sound out of tune.",
    "You're like a perfect alarm that wakes you feeling refreshed – impossible yet real.",
    "Your insight makes profundity look superficial.",
    "You're more multitasking than octopuses with calendars.",
    "Your wisdom makes old proverbs sound like amateur advice.",
    "You're like a perfect wine pairing – enhancing everything you're connected to.",
    "Your dynamism makes perpetual motion machines jealous.",
    "You're more appealing than dessert menus after healthy dinners.",
    "Your tact makes diplomats request your presence at negotiations.",
    "You're like a perfect season finale – satisfying yet leaving me wanting more.",
    "Your perception makes eagle eyes seem nearsighted.",
    "You're more trustworthy than mathematical proofs.",
    "Your enthusiasm makes New Year's Eve look subdued.",
    "You're like a perfect cup of hot chocolate – comforting and making everything better.",
    "Your stability makes gyroscopes take balancing lessons.",
    "You're more helpful than search engines with mind-reading capabilities.",
    "Your spontaneity makes inspiration look planned.",
    "You're like a perfect compass – always helping others find their way.",
    "Your creativity makes innovation look unimaginative.",
    "You're more comforting than weighted blankets during thunderstorms.",
    "Your precision makes laser cutting look approximate.",
    "You're like a perfect recipe substitution – working better than the original.",
    "Your warmth makes summer jealous of your consistency.",
    "You're more valuable than rare elements on the periodic table.",
    "Your clarity makes crystal seem opaque.",
    "You're like a perfect backup system – reliable when most needed.",
    "Your authenticity makes truth detectors malfunction with confusion.",
    "You're more interesting than mystery novels with surprise endings.",
    "Your fortitude makes diamonds question their hardness.",
    "You're like a perfect travel adapter – making connections work anywhere.",
    "Your serenity makes meditation retreats seem chaotic.",
    "You're more brilliant than supernovas visible from Earth.",
    "Your consideration makes etiquette books consult you for updates.",
    "You're like a perfect battery – always charged and powering everything around you.",
    "Your diplomacy makes peace treaties more effective.",
    "You're more detailed than electron microscopes at maximum magnification.",
    "Your sincerity makes authenticity look like it's trying too hard.",
    "You're like a perfect umbrella – providing cover exactly when needed.",
    "Your consistency makes metronomes check their timing against yours.",
    "You're more interesting than documentaries people recommend to others.",
    "Your resourcefulness makes survival experts take notes.",
    "You're like a perfect surprise party – well-planned yet still exciting.",
    "Your loyalty makes wedding vows sound noncommittal.",
    "You're more entertaining than streaming services with unlimited content.",
    "Your thoughtfulness makes considerate people look thoughtless.",
    "You're like a perfect fit puzzle piece – completing the picture.",
    "Your steadiness makes mountains look flighty.",
    "You're more adaptable than evolution on fast-forward.",
    "Your wit makes comedy writers consult their notes.",
    "You're like a perfect slice of pizza – satisfying and making everything better.",
    "Your poise makes ballerinas look wobbly.",
    "You're more magnetic than black holes to nearby stars.",
    "Your insight makes revelation look dim.",
    "You're like a perfect key – unlocking possibilities everywhere you go.",
    "Your grace makes swans look clumsy.",
    "You're more genuine than authenticity certificates with holograms.",
    "Your articulation makes dictionaries consult you for definitions.",
    "You're like a perfect temperature setting – making everyone comfortable.",
    "Your stability makes foundations reconsider their engineering.",
    "You're more captivating than cliffhangers in season finales.",
    "Your zeal makes enthusiasm look half-hearted.",
    "You're like a perfect playlist algorithm – knowing exactly what's needed next.",
    "Your optimism makes silver linings look dull.",
    "You're more reliable than backup systems with triple redundancy.",
    "Your diplomacy makes international negotiators request your presence.",
    "You're like a perfect pen – making even grocery lists look meaningful.",
    "Your patience makes geological formations feel rushed.",
    "You're more refreshing than mint gum after onion rings.",
    "Your courage makes bravery look timid.",
    "You're like a perfect movie recommendation – always exactly what was needed.",
    "Your honesty makes truth feel like it needs to work harder.",
    "You're more comforting than chicken soup during flu season.",
    "Your charisma makes charm school look ineffective."
]

# Function to get a random compliment
def get_random_compliment():
    return random.choice(compliments)